[package]
name = "aoc2018"
version = "0.1.0"
authors = ["zhangteng <zhangteng.mark@bytedance.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name="day1"
path="src/day1/main.rs"

[dependencies]
